name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  testsuite:
    uses: cakephp/.github/.github/workflows/testsuite-with-db.yml@5.x
    secrets: inherit

  cs-stan:
    name: Coding Standard & Static Analysis
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl
        coverage: none
        tools: cs2pr, vimeo/psalm:5, phpstan:1.10

    - name: Composer Install
      run: composer install

    - name: Run phpcs
      run: vendor/bin/phpcs --report=checkstyle src/ tests/ | cs2pr

    - name: Run psalm
      if: always()
      run: psalm --output-format=github

    - name: Run phpstan
      if: always()
      run: phpstan analyse
